### ISSUE TITLE
another example to add 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [rainyl/opencv_dart.examples#4]
i made a port from an old project i had from python to flutter so it can be served as an example here https://github.com/abdelaziz-mahdy/flutter_toon_it

**Comment by rainyl** [comment]
Great! You can open a PR to add it if you want, or I will add it 😄

**Comment by abdelaziz-mahdy** [comment]
Will add it as a pr, tomorrow then

**Comment by abdelaziz-mahdy** [comment]
sorry i forgot to add, this is the pr https://github.com/rainyl/awesome-opencv_dart/pull/5

**Comment by rainyl** [comment]
never mind, I have merged it, thanks~
